# Digit Generator

Use this Notebook to random generate the set of digits that you will handwrite for your final project data collection step.

In [1]:
# Load libraries
import numpy as np
import scipy.stats as stats

# Creates a Uniform discrete random variable that samples values {0,1,2,...,9} with equal probability
X = stats.rv_discrete(values=(list(range(10)), np.ones(10)/10))

Now, sample values at random for each image/row.

# Tell me My Digits

## For Single-Digit Images (total of 30 images)

In [2]:
X.rvs(size=[30,1])

array([[4],
       [2],
       [4],
       [0],
       [2],
       [0],
       [5],
       [7],
       [9],
       [8],
       [7],
       [3],
       [0],
       [2],
       [3],
       [1],
       [4],
       [2],
       [7],
       [3],
       [9],
       [0],
       [4],
       [9],
       [8],
       [3],
       [2],
       [8],
       [1],
       [5]])

## For Two-Digit Images (Total of 30 images)

In [3]:
X.rvs(size=[30,2])

array([[4, 6],
       [8, 8],
       [7, 7],
       [4, 4],
       [1, 5],
       [4, 7],
       [4, 0],
       [2, 6],
       [0, 5],
       [9, 5],
       [4, 9],
       [6, 8],
       [2, 0],
       [5, 7],
       [8, 9],
       [4, 2],
       [8, 2],
       [3, 9],
       [0, 6],
       [9, 8],
       [2, 7],
       [1, 3],
       [3, 9],
       [0, 2],
       [3, 1],
       [0, 6],
       [0, 4],
       [0, 1],
       [1, 2],
       [6, 2]])

## For Three-Digit Images (Total of 40 images)

In [4]:
X.rvs(size=[40,3])

array([[0, 6, 6],
       [2, 4, 1],
       [9, 0, 7],
       [2, 4, 2],
       [9, 1, 3],
       [2, 7, 6],
       [9, 5, 7],
       [9, 7, 1],
       [7, 3, 3],
       [1, 0, 6],
       [7, 6, 7],
       [8, 8, 9],
       [4, 8, 4],
       [6, 3, 2],
       [5, 7, 3],
       [6, 1, 2],
       [2, 8, 5],
       [8, 1, 2],
       [9, 2, 7],
       [2, 5, 0],
       [2, 6, 0],
       [5, 1, 0],
       [4, 7, 4],
       [0, 6, 2],
       [9, 5, 8],
       [8, 9, 9],
       [4, 5, 9],
       [2, 9, 6],
       [4, 5, 9],
       [1, 0, 5],
       [3, 8, 1],
       [0, 6, 8],
       [6, 8, 4],
       [8, 5, 3],
       [2, 1, 7],
       [2, 8, 8],
       [0, 3, 1],
       [9, 6, 7],
       [3, 7, 2],
       [2, 1, 7]])

---